<?xml version="1.0"?>

<package format="2">
  <name>Robotic-Dog-Interface-AIMS-Lab</name>
  <version>0.0.0</version>
  <description>Unitree Go1 body trajectory tracking, joint torque experiments, and offline analysis of supervised walking and motion-capture data.</description>
  <maintainer email="zhou1043@purdue.edu"></maintainer>
  <license>MIT</license>
  
  <buildtool_depend>catkin</buildtool_depend>
</package>